<?php
/**
 * This file has been @generated by a phing task by {@link BuildMetadataPHPFromXml}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return [
    'generalDesc' => [
        'NationalNumberPattern' => '(?:[23]\\d|[48]8)\\d{3}|(?:[57]\\d|90)\\d{5}',
        'PossibleLength' => [
            0 => 5,
            1 => 7,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'fixedLine' => [
        'NationalNumberPattern' => '(?:38[0-8]|48[4-9])\\d\\d|(?:2[02-9]|3[4-7]|88)\\d{3}',
        'ExampleNumber' => '22123',
        'PossibleLength' => [
            0 => 5,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'mobile' => [
        'NationalNumberPattern' => '57[2-5]\\d{4}|(?:5[0-689]|7[013-7])\\d{5}',
        'ExampleNumber' => '5912345',
        'PossibleLength' => [
            0 => 7,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'tollFree' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'premiumRate' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'sharedCost' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'personalNumber' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'voip' => [
        'NationalNumberPattern' => '90[1-9]\\d{4}',
        'ExampleNumber' => '9010123',
        'PossibleLength' => [
            0 => 7,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'pager' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'uan' => [
        'NationalNumberPattern' => '(?:3[03]|900\\d)\\d{3}',
        'ExampleNumber' => '30123',
        'PossibleLength' => [
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'voicemail' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'noInternationalDialling' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'id' => 'VU',
    'countryCode' => 678,
    'internationalPrefix' => '00',
    'sameMobileAndFixedLinePattern' => false,
    'numberFormat' => [
        0 => [
            'pattern' => '(\\d{3})(\\d{4})',
            'format' => '$1 $2',
            'leadingDigitsPatterns' => [
                0 => '[579]',
            ],
            'nationalPrefixFormattingRule' => '',
            'domesticCarrierCodeFormattingRule' => '',
            'nationalPrefixOptionalWhenFormatting' => false,
        ],
    ],
    'intlNumberFormat' => [
    ],
    'mainCountryForCode' => false,
    'leadingZeroPossible' => false,
    'mobileNumberPortableRegion' => false,
];
