<?php
/**
 * Class SampleTest
 *
 * @package Payplug
 */

/**
 * Sample test case.
 */
class SampleTest extends WP_UnitTestCase {

	public function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	/**
	 * A single example test.
	 */
	function test_sample() {
		// Replace this with some actual testing code.
		$this->assertTrue( true );
	}

}
