<?php

namespace Payplug\PayplugWoocommerce\Tests\phpunit\src\Model\HostedFields;

use Payplug\PayplugWoocommerce\Model\HostedFields;
use PHPUnit\Framework\TestCase;

class BaseHostedFields extends TestCase {

	protected $hostedFields;

	public function setUp(): void {

		$this->hostedFields = $this->getMockBuilder(HostedFields::class)
			->setConstructorArgs(['secret', 'api_key', 'identifier', 'api_key_secret'])
            ->onlyMethods(['get_api_key_secret', 'get_api_version', 'get_api_key', 'buildHashContent', 'limit_length'])
            ->getMock();

		parent::setUp(); // TODO: Change the autogenerated stub
	}

}
