<?php

namespace Payplug\PayplugWoocommerce\Tests\phpunit\src\Model\HostedFields;

use Payplug\PayplugWoocommerce\Model\HostedFields;

class populateGetTransaction extends BaseHostedFields {

	public function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function testPopulateGetTransactionWithEmptyPaymentId() {
		$this->expectException(\InvalidArgumentException::class);
		$this->expectExceptionMessage('Parameters array cannot be empty');

		$this->hostedFields->populateGetTransaction('');
	}



}
